version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongo-serve
    ports:
      - "27018:27017"
    # volumes:
    #   - ./data:/data/db
    networks:
      - my-network
    restart: always
networks:
  my-network:
    driver: bridge